server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payload
              uri: lb://payload
              predicates:
                - Path=/payload/**
              filters:
                - StripPrefix=1
            - id: web
              uri: lb://webmodule
              predicates:
                - Path=/webmodule/**
              filters:
                - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
