spring:
  application:
    name: eurekaserver

server:
  port: 8761

eureka:
  instance:
    hostname: eurekaserver
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
  server:
    response-cache-update-interval-ms: 500
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 2000
    peer-eureka-nodes-update-interval-ms: 600000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/